permalink: pretty
theme: jekyll_patternbot
patternbot:
  layouts:
    default: |
      The default layout should be used for almost every single page, it includes the website's primary header and footer.
  title: "Vape Master"
  description: |
    A small local vape organization specializing in premium vape products.
  colors:
    background: "--color-secondary"
    accent: "--color-primary"
    patterns:
      brand.logos: "--color-primary"
  rationales:
    typefaces.primary: |
      Proxima Nova was selected because it is legible and can be used as both headings and body copy.
    colors.primary: |
      The primary colours represent the premium brand on the website. This colour should be used for text on a white background only to keep the text ledgible.
    colors.secondary: |
      The secondary colour is to be used for the background on the website.
collections:
  products:
    output: true

defaults:
  - scope:
      path: _products
    values:
      layout: product
