title: "Buttons"
description: |
Buttons should be used in situations where a dramatic, obvious action is required.

patterns:
  light:
    fields:
      -name: text
      type: string
      example: "View products"
      -name: url
      type: url
      example: "/products/"
      title: "Light"
      description: |
      Default to using the light button. It should always be used first.
      width: "12em"
      underline:
        title: "Underline"
        description: |
        Always use this button on the top of the page for other store information.
